GhostStead org and source
googledatastudio/ds-data-registry pull request #413
Opened 2020-11-01 17:16 UTC by ghoststead

Add an organization and source for GhostStead (https://www.ghoststead.com/)

2020-11-01 17:23 UTC, ghoststead commented
@googlebot I signed it!

2020-11-04 18:36 UTC, pfrisella requested changes

2020-11-04 18:36 UTC, pfrisella commented on organizations/ghoststead.json
> +  "id": "EBAY",
Add the correct the organization details.

2020-11-04 20:27 UTC, ghoststead commented on organizations/ghoststead.json
> +  "id": "EBAY",
Done.  Force pushed for fix the previous broken commit.

2020-11-05 17:51 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2020-11-05 17:52 UTC, merged