Tables source
googledatastudio/ds-data-registry pull request #424
Opened 2020-12-07 21:36 UTC by aniketvp-g

Add a source for Google Tables by Area 120

2020-12-08 18:09 UTC, pfrisella requested changes

2020-12-08 18:09 UTC, pfrisella commented on sources/google_tables_area120.json
> +  "id": "GOOGLE_TABLES",
ID and filename should match. I suggest renaming file name to google_tables.json

2020-12-08 18:09 UTC, pfrisella commented on sources/google_tables_area120.json
> +  "name": "Google Tables by Area 120 (Beta)",
the purpose of the source is simply to identify a data source, probably can drop the (Beta) part.

2020-12-09 21:19 UTC, aniketvp-g commented on sources/google_tables_area120.json
> +  "id": "GOOGLE_TABLES",
Updated ID to GOOGLE_TABLES_AREA120 instead since we must keep the Area 120 tag.

2020-12-09 21:19 UTC, aniketvp-g commented on sources/google_tables_area120.json
> +  "name": "Google Tables by Area 120 (Beta)",
Done.

2020-12-10 17:23 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2020-12-10 17:23 UTC, merged