Add new source Affilbox and organization marketing.bi
googledatastudio/ds-data-registry pull request #425
Opened 2020-12-09 15:57 UTC by banhetom

I want to add new organization Marketing.bi and new source Affilbox
Could you please merge the code?

2020-12-09 15:58 UTC, banhetom commented
@googlebot I signed it!

2020-12-09 16:04 UTC, banhetom commented
@googlebot I fixed it.

2020-12-10 19:05 UTC, pfrisella requested changes

2020-12-10 19:05 UTC, pfrisella commented on sources/affilbox.json
> +}
`dataVisibility` property is missing.

See https://github.com/googledatastudio/ds-data-registry#add-a-source

2020-12-16 23:43 UTC, pfrisella approved these changes
Thanks for updating. LGTM!

2020-12-16 23:43 UTC, merged