Itens about two conectors.
googledatastudio/ds-data-registry pull request #427
Opened 2020-12-15 17:21 UTC by Akira0i

These two are about an conector named Agendor and another named Currency Converter

2020-12-16 14:51 UTC, Akira0i commented
@googlebot I signed it!

2020-12-16 23:53 UTC, pfrisella requested changes
The purpose of this is not to add your connectors. It is to add descriptions of data sources. For example, if 2 developers create a Twitter connector, they do not both register the twitter data source here for each connector.  Only 1 twitter data source registered in this repo and each connector would reference the same source. For your currency source, make it generic so that any currency related connector will use this source.

2020-12-16 23:53 UTC, pfrisella commented on organizations/agendor.json
> +  "orgUrl": "https://api.agendor.com.br/",
The org link is to learn more about the organization. This should probably just be https://www.agendor.com.br/

2020-12-16 23:53 UTC, pfrisella commented on organizations/currency_conversion.json
> +{
If you're adding a generic currency data source then I suggest you don't add an organization because there is no org that makes sense. Remove this file.

2020-12-16 23:53 UTC, pfrisella commented on sources/agendor.json
> +  "sourceUrl": "https://api.agendor.com.br/",
This link is to learn more about the source, not necessarily that it comes from the API. I suggest using https://www.agendor.com.br/

2020-12-16 23:53 UTC, pfrisella commented on sources/currency_conversion.json
> +{
If this if for a general currency data source then I suggest using CUSTOM_CURRENCY as the ID and name Custom Currency.

Remove the organization because it doest belong to a single organization.
Remove the source url.

2021-01-04 13:34 UTC, Akira0i reviewed
All changes requested have been made.

2021-01-05 21:20 UTC, pfrisella requested changes

2021-01-05 21:20 UTC, pfrisella commented on sources/currency_conversion.json
> +{
the ID needs to match the filename.

If this if for a general currency data source then I suggest using CUSTOM_CURRENCY as the ID and name Custom Currency.

Remove the organization because it doest belong to a single organization.
Remove the source url.

2021-01-07 14:07 UTC, Akira0i reviewed
Removed the organization and the source url from currency conversion and ajusted the ID and name.

2021-01-07 20:31 UTC, pfrisella approved these changes

2021-01-07 20:31 UTC, merged