Create woocommerce
googledatastudio/ds-data-registry pull request #434
Opened 2020-12-30 02:29 UTC by powermyanalytics

2021-01-05 21:23 UTC, pfrisella requested changes
There is no source file, is that intended?

2021-01-05 21:23 UTC, pfrisella commented on organizations/woocommerce
> +
file is missing .json extension

2021-01-05 22:14 UTC, powermyanalytics commented
Can you please add ".json" at the end - my bad...

2021-01-12 12:42 UTC, powermyanalytics commented
Hi Pete,

 

Can we get these published?  We have been waiting over 2 weeks to submit WooCommerce to the gallery.  I resubmitted the Source and Organization for WooCommerce a couple days ago to try to get those going again.

 

Cheers

 

Morgan

 

  <https://www.powermyanalytics.com/images/powermyanalytics2.png> 

 <http://www.powermyanalytics.com/> http://www.powermyanalytics.com/

Data Connectors + Call Tracking

(800) 746-3083, x701

 

From: Pete Frisella <notifications@github.com> 
Sent: Tuesday, January 5, 2021 4:24 PM
To: googledatastudio/ds-data-registry <ds-data-registry@noreply.github.com>
Cc: Power My Analytics <morgan.jones@powermyanalytics.com>; Author <author@noreply.github.com>
Subject: Re: [googledatastudio/ds-data-registry] Create woocommerce (#434)

 

@pfrisella requested changes on this pull request.

There is no source file, is that intended?

  _____  

In organizations/woocommerce <https://github.com/googledatastudio/ds-data-registry/pull/434#discussion_r552203317> :

> @@ -0,0 +1,8 @@
+  

file is missing .json extension

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/googledatastudio/ds-data-registry/pull/434#pullrequestreview-562147052> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AJIBHQZPOPL7SCXL2W2HULDSYN7P3ANCNFSM4VN2V53A> .  <https://github.com/notifications/beacon/AJIBHQ3XPD5T33WJNYMARM3SYN7P3A5CNFSM4VN2V53KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOEGA253A.gif>

2021-01-12 18:14 UTC, pfrisella commented
Resolved with another PR

2021-01-12 18:14 UTC, closed without merging