Create zoho_desk.json
googledatastudio/ds-data-registry pull request #435
Opened 2020-12-30 18:59 UTC by datawisdomStudio

Add Zoho Desk Service to the registry

2020-12-30 19:03 UTC, datawisdomStudio commented
@googlebot I signed it!

2020-12-30 19:09 UTC, datawisdomStudio commented
@googlebot I signed it!

2020-12-30 19:24 UTC, datawisdomStudio commented
@googlebot I signed it!

2021-01-05 21:26 UTC, pfrisella requested changes

2021-01-05 21:26 UTC, pfrisella commented on sources/zoho_desk.json
> +  "categories": ["SOCIAL"],
perhaps CUSTOMER_SUPPORT or CRM are more appropriate?

2021-01-07 21:13 UTC, datawisdomStudio commented on sources/zoho_desk.json
> +  "categories": ["SOCIAL"],
Agree, thanks!

2021-01-12 18:16 UTC, pfrisella approved these changes
LGTM. Thanks for updating.

2021-01-12 18:16 UTC, merged