Create miva
googledatastudio/ds-data-registry pull request #436
Opened 2020-12-30 23:13 UTC by powermyanalytics

2021-01-05 21:27 UTC, pfrisella requested changes

2021-01-05 21:27 UTC, pfrisella commented on organizations/miva
> +{
file is missing .json extension

2021-01-05 22:15 UTC, powermyanalytics commented on organizations/miva
> +{
Can you please add to the end?  I forgot...

2021-01-06 00:09 UTC, powermyanalytics commented on organizations/miva
> +{
Or please let me know how I add the extension...not sure how to edit this.

2021-01-12 18:19 UTC, pfrisella commented
Resolved in another PR

2021-01-12 18:19 UTC, closed without merging