Add Matomo to Sources
googledatastudio/ds-data-registry pull request #445
Opened 2021-01-12 09:42 UTC by wpxgit

Adding Matomo Data Source to provide a Data Studio Connector for Matomo Analytics (https://matomo.org/)

2021-01-12 09:43 UTC, wpxgit commented
@googlebot I signed it!

2021-01-12 18:20 UTC, pfrisella requested changes

2021-01-12 18:20 UTC, pfrisella commented on sources/matomo.json
> +  "id": "MATOMO_ANALYTICS",
The filename and id should match. Either change filename to matomo_analytics or change id to MATOMO

2021-01-12 19:44 UTC, wpxgit commented on sources/matomo.json
> +  "id": "MATOMO_ANALYTICS",
Thanks, changed the id

2021-01-21 08:22 UTC, wpxgit commented
@pfrisella i've made the changes - can you please review? Thanks!

2021-01-22 20:06 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-01-22 20:06 UTC, merged