Create ynab.json source.
googledatastudio/ds-data-registry pull request #446
Opened 2021-01-14 13:54 UTC by george-dilthey

New source for a connector.

2021-01-14 13:56 UTC, george-dilthey commented
@googlebot I signed it!

2021-01-22 20:08 UTC, pfrisella requested changes

2021-01-22 20:08 UTC, pfrisella commented on sources/ynab.json
> +  "organization": "You Need A Budget LLC",
organization needs to be an ID referencing an org. See how to add an org: https://github.com/googledatastudio/ds-data-registry#add-an-organization

2021-02-25 18:37 UTC, pfrisella commented
Closing due to inactivity. If you'd still like to add this then send a new pull request and address the comments that were left in this PR.

2021-02-25 18:37 UTC, closed without merging