Create george_dilthey.json
googledatastudio/ds-data-registry pull request #449
Opened 2021-01-22 20:28 UTC by george-dilthey

Added george_dilthey.json

2021-01-26 19:22 UTC, pfrisella requested changes

2021-01-26 19:22 UTC, pfrisella commented on organizations/george_dilthey.json
> +{
Which source belongs to this org? I suspect this is for YNAB but the org should be the org of YNAB. Note that the sources and orgs do not represent a connector, they simply define a data source.

2021-01-26 19:25 UTC, george-dilthey commented on organizations/george_dilthey.json
> +{
Hi @pfrisella! I'm new to this, so thanks for bearing with me! I'm building out a connector using the YNAB API, but I'm not associated with YNAB at all, so I'm not 100% sure what the SOP should be here. I didn't want to create a new org saying that I represent YNAB, but I also wanted it to be clear that the data source is coming from YNAB. Let me know what you think and I can edit things accordingly.

2021-01-29 00:52 UTC, pfrisella commented on organizations/george_dilthey.json
> +{
This repo just describes/identifies data sources, all of which is public information. It does not represent your connector or associate you with a company.

2021-02-25 18:37 UTC, pfrisella commented
Closing due to inactivity.

2021-02-25 18:37 UTC, closed without merging

2021-02-25 19:14 UTC, george-dilthey commented
Hey Pete. Not sure why this got closed. I was waiting on a review from you for the latest version, and the source that was closed relied on this. I'm happy to submit again if need be, just let me know.