add sources from clickforce holmes ads
googledatastudio/ds-data-registry pull request #452
Opened 2021-01-26 09:59 UTC by MIGOdanis

2021-01-26 10:07 UTC, MIGOdanis commented
@googlebot I signed it!

2021-01-26 19:19 UTC, pfrisella requested changes

2021-01-26 19:19 UTC, pfrisella commented on organizations/clickforce.json
> +  "id": "Clickforce",
CLICKFORCE

2021-01-26 19:19 UTC, pfrisella commented on sources/holmesads.json
> +  "id": "HOLMES ADS",
it should match the filename.
HOLMESADS

2021-01-26 19:19 UTC, pfrisella commented on sources/holmesads.json
> +  "organization": "Clickforce",
CLICKFORCE

2021-01-27 02:21 UTC, MIGOdanis commented
@pfrisella thank you.  I fixed it.

2021-01-29 00:42 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-01-29 00:42 UTC, merged