Create trustsales.json
googledatastudio/ds-data-registry pull request #475
Opened 2021-03-04 09:22 UTC by syhoai99

REGISINFO

2021-03-04 09:28 UTC, syhoai99 commented
@googlebot I signed it!

2021-03-04 09:30 UTC, syhoai99 commented
please help add my datasource

2021-03-23 17:27 UTC, pfrisella requested changes

2021-03-23 17:27 UTC, pfrisella commented on sources/trustsales.json
> +  "id": "TRUSTSALE",
ID should match the filename

2021-03-24 04:33 UTC, closed without merging