Add EASYAPPREPORTS organization and sources
googledatastudio/ds-data-registry pull request #488
Opened 2021-03-23 20:10 UTC by lspecian

Add EASYAPPREPORTS organization and sources EASYAPPREPORTS_APPSTORECONNECT and EASYAPPREPORTS_PLAYCONSOLE

2021-04-09 21:32 UTC, pfrisella commented
It looks like these sources should just be Google Play by Google and App Store Connect by Apple. The goal is to register the underlying data source, not connector specific versions. For example, if there are multiple connectors that query Twitter data, they all use the same TWITTER source, there isn't an entry for each connector.

2021-04-11 08:13 UTC, lspecian commented
hello @pfrisella , I initially misunderstood the purpose of the files, I believe that the sources are now changed to reflect the proper information.

2021-04-12 16:28 UTC, pfrisella requested changes

2021-04-12 16:28 UTC, pfrisella commented on sources/apple_appstoreconnect.json
> +  "id": "APPLE_APPSTORECONNECT",
```suggestion
  "id": "APP_STORE_CONNECT",
```

2021-04-12 16:28 UTC, pfrisella commented on sources/apple_appstoreconnect.json
> +  "id": "APPLE_APPSTORECONNECT",
if the ID is changed as suggested then the file name should be app_store_connect.json

2021-04-12 16:28 UTC, pfrisella commented on sources/google_playconsole.json
> +  "id": "GOOGLE_PLAYCONSOLE",
```suggestion
  "id": "GOOGLE_PLAY_CONSOLE",
```

2021-04-12 16:28 UTC, pfrisella commented on sources/google_playconsole.json
> +{
if the ID is changed as suggested then the file name should be google_play_console.json

2021-04-12 21:12 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-04-12 21:12 UTC, merged