adding company and source
googledatastudio/ds-data-registry pull request #499
Opened 2021-04-14 07:31 UTC by viskvortsov

2021-04-19 14:08 UTC, viskvortsov commented
@pfrisella
Would you like us to do something else?

2021-04-19 17:52 UTC, pfrisella requested changes

2021-04-19 17:52 UTC, pfrisella commented on sources/vashkpi.json
> +  "id": "kpi_indicators",
Review the instructions at: https://github.com/googledatastudio/ds-data-registry#add-a-source

ID should match filename, all uppercase.

2021-04-19 17:52 UTC, pfrisella commented on sources/vashkpi.json
> +  "organization": "vashkpi",
uppercase

2021-04-20 02:25 UTC, viskvortsov commented on sources/vashkpi.json
> +  "id": "kpi_indicators",
Done

2021-04-20 02:26 UTC, viskvortsov commented
@pfrisella thanks for your remarks.
I've commited new version

2021-04-20 18:48 UTC, pfrisella approved these changes

2021-04-20 18:49 UTC, merged