Create freshworks_crm.json
googledatastudio/ds-data-registry pull request #503
Opened 2021-04-30 07:03 UTC by michaes-jivrus

Adding source for Freshworks CRM

2021-04-30 07:06 UTC, michaes-jivrus commented
Could you please review and merge this new source for Freshworks CRM?

2021-05-03 05:48 UTC, michaes-jivrus commented
@pfrisella @castroalves @mattyb @lmanolov @paramaw 
appreciate it if one of you could review and merge this

2021-05-03 17:35 UTC, pfrisella requested changes

2021-05-03 17:35 UTC, pfrisella commented on sources/freshworks_crm.json
> +  "id": "FRESHWORKS-CRM",
```suggestion
  "id": "FRESHWORKS_CRM",
```

2021-05-04 00:46 UTC, michaes-jivrus commented
@pfrisella I have made the changes and pushed the code. Please check

2021-05-04 19:41 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-05-04 19:42 UTC, merged