Added Clickie source
googledatastudio/ds-data-registry pull request #506
Opened 2021-05-14 20:15 UTC by peybol

2021-05-17 19:45 UTC, pfrisella requested changes

2021-05-17 19:45 UTC, pfrisella commented on sources/clickie.json
> +  "organization": "Clickie SPA",
not a valid org. See https://github.com/googledatastudio/ds-data-registry#add-an-organization

2021-05-17 20:05 UTC, peybol commented on sources/clickie.json
> +  "organization": "Clickie SPA",
fixed, thanks.

2021-05-18 21:20 UTC, pfrisella requested changes

2021-05-18 21:20 UTC, pfrisella commented on organizations/clickie.json
> +  "id": "CLICKIE_SPA",
ID and filename must match. filename should be clickie_spa.json

2021-05-18 21:24 UTC, peybol commented on organizations/clickie.json
> +  "id": "CLICKIE_SPA",
Sorry, done. Thanks.

2021-05-19 16:57 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-05-19 16:57 UTC, merged