Add Makeshop Source
googledatastudio/ds-data-registry pull request #507
Opened 2021-05-15 15:59 UTC by 1987yama3

Adding Makeshop Data Source to provide a Data Studio Connector for Makeshop eCommerce Platform (https://www.makeshop.jp/)

2021-05-17 19:44 UTC, pfrisella requested changes

2021-05-17 19:44 UTC, pfrisella commented on sources/makeshop.json
> +  "organization": "GMO",
This org needs to be added too if it doesn't exist.
https://github.com/googledatastudio/ds-data-registry#add-an-organization

2021-05-18 00:06 UTC, 1987yama3 commented on sources/makeshop.json
> +  "organization": "GMO",
@pfrisella Thanks. I add org.

2021-05-18 21:26 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-05-18 21:26 UTC, merged