Add DOIT-BI organization, source and category
googledatastudio/ds-data-registry pull request #511
Opened 2021-05-18 16:58 UTC by doit-bi

2021-05-18 17:02 UTC, doit-bi commented
@googlebot I signed it!

2021-05-18 17:12 UTC, doit-bi commented
@googlebot I fixed it

2021-05-18 17:15 UTC, doit-bi-do commented
@googlebot I consent.

2021-05-18 17:17 UTC, doit-bi-do submitted a review, later dismissed

2021-05-18 17:17 UTC, doit-bi-do reviewed
ok

2021-05-18 17:23 UTC, doit-bi-do reviewed
All okey

2021-05-18 17:26 UTC, doit-bi commented
@pfrisella Could you review and merge please

2021-05-18 21:32 UTC, pfrisella requested changes

2021-05-18 21:32 UTC, pfrisella commented on organizations/doit-bi.json
> +{
make the filename underscores to match the ID. doit_bi.json

2021-05-18 21:32 UTC, pfrisella commented on sources/doit-bi.json
> +{
make the filename underscores to match the ID. doit_bi.json

2021-05-19 06:39 UTC, doit-bi commented
@pfrisella I renamed files. Can you check?

2021-05-19 16:58 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-05-19 16:58 UTC, merged