Add TryBooking
googledatastudio/ds-data-registry pull request #513
Opened 2021-05-21 02:31 UTC by zebby-nick

This will add a new Org and Source for the TryBooking API.

2021-05-21 02:32 UTC, zebby-nick commented
@googlebot I signed it!

2021-05-24 18:32 UTC, pfrisella requested changes

2021-05-24 18:32 UTC, pfrisella commented on organizations/trybooking
> +{
File needs to have .json extension.

2021-05-24 18:32 UTC, pfrisella commented on sources/trybooking
> +{
File needs to have .json extension.

2021-05-24 18:32 UTC, pfrisella commented on sources/trybooking
> +  "id": "trybooking",
ID needs to be uppercase

2021-05-26 02:58 UTC, zebby-nick commented
Fixed extensions and changed ID to uppercase.

2021-06-02 16:30 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-06-02 16:30 UTC, merged