Foundant glm slm source addition
googledatastudio/ds-data-registry pull request #515
Opened 2021-06-01 12:07 UTC by aszalacinski

- removes duplicate source file called glmslm
- updates original source file of glm

2021-06-02 16:34 UTC, pfrisella requested changes

2021-06-02 16:34 UTC, pfrisella commented on sources/glm.json
> +  "id": "GLMSLM",
Keep the ID the same since it's already in use.

2021-07-08 18:51 UTC, aszalacinski commented on sources/glm.json
> +  "id": "GLMSLM",
fixed

2021-07-19 12:38 UTC, aszalacinski commented
The change request was completed 11 days ago. Can this be merged now? Please advise.

2021-08-10 19:31 UTC, pfrisella commented
Closing due to inactivity.

2021-08-10 19:31 UTC, closed without merging