Add data sources
googledatastudio/ds-data-registry pull request #518
Opened 2021-06-09 15:34 UTC by dessibelle

2021-06-18 16:55 UTC, pfrisella requested changes

2021-06-18 16:55 UTC, pfrisella commented on sources/sizmek_advertising_suite.json
> +  "organization": "SIZMEK_ADVERTISING_SUITE",
Can you use existing SIZMEK org? https://github.com/googledatastudio/ds-data-registry/blob/master/organizations/sizmek.json

2021-06-18 18:43 UTC, dessibelle commented on sources/sizmek_advertising_suite.json
> +  "organization": "SIZMEK_ADVERTISING_SUITE",
Thanks for pointing that out, I was sure that's what I had done cause I saw there was one, but I must have messed up. I'll fix that!

2021-06-18 18:46 UTC, dessibelle commented on sources/sizmek_advertising_suite.json
> +  "organization": "SIZMEK_ADVERTISING_SUITE",
I've rebased on master and adjusted `SIZMEK_ADVERTISING_SUITE` organization now.

2021-06-25 17:33 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-06-25 17:41 UTC, pfrisella commented
Looks like CLA bot is stuck. Can you rebase and push again?

2021-06-26 11:46 UTC, dessibelle commented
Thanks, I've rebased and pushed again. Looks like the CLA bot check passed this time :)

2021-06-30 18:35 UTC, pfrisella approved these changes
Let's try again

2021-06-30 18:35 UTC, merged