feat: add automotus org and data source
googledatastudio/ds-data-registry pull request #553
Opened 2021-08-04 18:02 UTC by zanebclark

2021-08-05 19:05 UTC, zanebclark commented
@googlebot I signed it!

2021-08-10 16:29 UTC, zanebclark commented
@pfrisella , a review at your earliest convenience would be greatly appreciated.

2021-08-10 19:27 UTC, pfrisella requested changes

2021-08-10 19:27 UTC, pfrisella commented on sources/automotus_insights.json
> +  "organization": "automotus_inc",
AUTOMOTUS_INC

2021-08-11 16:17 UTC, zanebclark commented on sources/automotus_insights.json
> +  "organization": "automotus_inc",
🤦 

Great catch. I've addressed this

2021-08-12 14:54 UTC, zanebclark commented
@pfrisella , this one should be good to go now. Thanks for your review. 

Quick question for you: 
Is this the right place to file bugs and feature requests for community connectors? 
https://issuetracker.google.com/issues?q=componentid:345845%20status:open#

Or, is this a more appropriate location:

2021-08-17 17:10 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-08-17 17:12 UTC, pfrisella commented
> @pfrisella , this one should be good to go now. Thanks for your review.
> 
> Quick question for you:
> Is this the right place to file bugs and feature requests for community connectors?
> https://issuetracker.google.com/issues?q=componentid:345845%20status:open#
> 
> Or, is this a more appropriate location:
> https://support.google.com/datastudio/community?hl=en

The issue tracker. This is also covered in the docs: https://developers.google.com/datastudio/connector/support

2021-08-17 17:12 UTC, merged