add whitebox api source
googledatastudio/ds-data-registry pull request #555
Opened 2021-08-07 08:20 UTC by LongNguyen1012

WhiteBox API is an internal project created to ingest data from internal APIs for internal usage. I would like to include this source in the Gallery in order to share this with other coworkers

2021-08-07 08:23 UTC, LongNguyen1012 commented
@googlebot I signed it!

2021-08-10 19:31 UTC, pfrisella requested changes

2021-08-10 19:31 UTC, pfrisella commented on sources/whitebox.json
> +  "organization": "WHITEBOX",
This organization doesn't exist. You'll need to add it.

2021-08-17 17:13 UTC, pfrisella approved these changes

2021-08-17 17:14 UTC, merged