Adding source and org for Papercut
googledatastudio/ds-data-registry pull request #564
Opened 2021-08-20 16:28 UTC by robertogallardo

2021-08-20 16:35 UTC, robertogallardo commented
@googlebot I signed it!

2021-09-07 18:47 UTC, pfrisella requested changes

2021-09-07 18:47 UTC, pfrisella commented on sources/papercut_hive.json
> +  "id": "PAPERCUT HIVE",
PAPERCUT_HIVE

2021-10-01 22:18 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-10-01 22:18 UTC, merged