Create gaannotations.json
googledatastudio/ds-data-registry pull request #567
Opened 2021-08-26 06:47 UTC by GAannotations-com

2021-09-07 08:40 UTC, GAannotations-com commented
@googlebot I signed it!

2021-09-07 18:49 UTC, pfrisella requested changes

2021-09-07 18:49 UTC, pfrisella commented on sources/gaannotations.json
> +  "organization": "GAANNOTATIONS",
The GAANNOTATIONS org does not exist. You'll also need to add it. See https://github.com/googledatastudio/ds-data-registry#add-an-organization

2021-09-08 19:02 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-09-08 19:02 UTC, merged