Integrate Anlyser Data  as a DataSource for Google Data Studio
googledatastudio/ds-data-registry pull request #574
Opened 2021-09-14 09:17 UTC by dkaraj

2021-09-16 20:48 UTC, pfrisella requested changes

2021-09-16 20:48 UTC, pfrisella commented on sources/anlyser.json
> +  "organization": "ANLYSER",
This org doesn't exist. It also needs to be added. See https://github.com/googledatastudio/ds-data-registry#add-an-organization

2021-09-17 07:50 UTC, dkaraj commented on sources/anlyser.json
> +  "organization": "ANLYSER",
I added it.

2021-09-21 17:50 UTC, pfrisella requested changes

2021-09-21 17:50 UTC, pfrisella commented on sources/anlyser.json
> +  "id": "ANLYSER_DATA",
File name needs to match ID. Either update filename to anlyser_data.json or ID to ANLYSER.

2021-10-01 22:19 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2021-10-01 22:19 UTC, merged