added mariadb source
googledatastudio/ds-data-registry pull request #638
Opened 2022-03-19 06:58 UTC by sakthivel-gox

2022-03-21 17:26 UTC, pfrisella requested changes

2022-03-21 17:26 UTC, pfrisella commented on sources/custom_api.json
> +    "id": "CUSTOM_API",
This is a bit too generic. Typically CUSTOM is used to describe a data type or format this is not specific to one service or product (e.g. importing generic data in JSON, CSV, XML, etc formats).

The goal is to help a user find a particular source. It should at least be descriptive of the data.

2022-03-23 18:21 UTC, pfrisella requested changes

2022-03-23 18:21 UTC, pfrisella commented on sources/custom_api.json
> +{
This source isn't any more useful than the last one since almost every source comes from an API. I suspect you probably don't need to add this source. If you are adding a source for a generic API connector then you can probably just use an existing CUSTOM source for your connector such as CUSTOM_JSON, CUSTOM_XML.

2022-03-24 12:40 UTC, sakthivel-gox commented on sources/custom_api.json
> +{
okay will use CUSTOM_JSON for that.

2022-03-24 12:40 UTC, sakthivel-gox commented on sources/custom_api.json
> +{
okay will use CUSTOM_JSON for that.

2022-04-01 17:11 UTC, pfrisella approved these changes

2022-04-01 17:11 UTC, merged