add VoIPstudio organization and source
googledatastudio/ds-data-registry pull request #643
Opened 2022-03-30 13:00 UTC by l7s

2022-04-01 17:13 UTC, pfrisella requested changes

2022-04-01 17:13 UTC, pfrisella commented on sources/voipstudio.json
> +  "id": "VOIPSTUDIO_CDR",
Filename should match ID. Update to voipstudio_cdr.json

2022-04-01 21:24 UTC, l7s commented on sources/voipstudio.json
> +  "id": "VOIPSTUDIO_CDR",
Filename has been changed as requested.

2022-04-04 19:51 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2022-04-04 19:51 UTC, merged