Add FluentPet source
googledatastudio/ds-data-registry pull request #650
Opened 2022-04-01 13:21 UTC by theycantalkdatastudio

2022-04-01 17:21 UTC, pfrisella commented
Can you provide some detail on what type of data this represents?

2022-04-04 06:39 UTC, theycantalkdatastudio commented
It allows users to export data gathered by https://fluent.pet/ mobile app. Info about who pressed the button, when, and in what kind of circumstances plus other metadata.

Columns exported by FluentPet's connector might include:
```
name,unique_id,event_type,is_human,species,breed,learner_language,birthdate,note,country,training_started_at,interaction_started_at,interaction_started_at_local,interaction_duration_in_seconds,teachers_in_household_count,learners_in_household_count,event_origin,board,all_data_json,buttons_count,all_buttons,all_contexts,button_1,button_1_concept,button_2,button_2_concept,button_3,button_3_concept,button_4,button_4_concept,button_5,button_5_concept,button_6,button_6_concept,button_7,button_7_concept,button_8,button_8_concept,button_9,button_9_concept,button_10,button_10_concept,button_11,button_11_concept,button_12,button_12_concept,button_13,button_13_concept,button_14,button_14_concept,button_15,button_15_concept,button_16,button_16_concept,button_17,button_17_concept,button_18,button_18_concept,button_19,button_19_concept,button_20,button_20_concept,context_1,context_2,context_3,context_4,context_5
```

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/102802035/161487077-86202291-96f2-4353-a58a-8541529bbf1c.png">
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/102802035/161487197-6a051456-679e-4823-844a-2333abdbe41a.png">

2022-04-04 19:56 UTC, pfrisella requested changes

2022-04-04 19:56 UTC, pfrisella commented on sources/fluentpet.json
> +  "categories": ["ANIMALS", "HARDWARE", "RESEARCH"],
Remove ANIMALS category, it's too specific as a data category.
Can you use IOT instead of HARDWARE?

2022-04-06 22:33 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2022-04-06 22:33 UTC, merged