Add SurveyToGo data source to data registry
googledatastudio/ds-data-registry pull request #657
Opened 2022-04-11 07:41 UTC by DoobloConnector

2022-04-11 08:16 UTC, DoobloConnector commented
Fixed CLA. Please check again

2022-04-13 18:08 UTC, DoobloConnector commented
Waiting for a review....

2022-04-19 08:01 UTC, DoobloConnector commented
@pfrisella 
Can we get a review?

2022-05-04 17:23 UTC, pfrisella requested changes

2022-05-04 17:23 UTC, pfrisella commented on sources/surveytogo.json
> +  "organization": "DOOBLO",
The organization does not exist. It will need to be added too.
See https://github.com/googledatastudio/ds-data-registry#add-an-organization

2022-05-05 05:21 UTC, DoobloConnector commented on sources/surveytogo.json
> +  "organization": "DOOBLO",
Added, Thanks.

2022-05-05 05:22 UTC, DoobloConnector commented
Added, Thanks.

On Wed, May 4, 2022 at 8:23 PM Pete Frisella ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In sources/surveytogo.json
> <https://github.com/googledatastudio/ds-data-registry/pull/657#discussion_r865087865>
> :
>
> > @@ -0,0 +1,9 @@
> +{
> +  "id": "SURVEYTOGO",
> +  "name": "SurveyToGo",
> +  "categories": ["TOOLS"],
> +  "organization": "DOOBLO",
>
> The organization does not exist. It will need to be added too.
> See
> https://github.com/googledatastudio/ds-data-registry#add-an-organization
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/googledatastudio/ds-data-registry/pull/657#pullrequestreview-962228635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYU6XBTTD3C55XKAOV5CGPTVIKXCZANCNFSM5TCI77CQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-09 16:58 UTC, pfrisella approved these changes
LGTM. Thanks for adding!

2022-05-09 17:00 UTC, merged